Resources:
  SampleRoleED81C780:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: amplify.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: AmplifyHostingStack/Sample/Role/Resource
  Sample9DACD4DE:
    Type: AWS::Amplify::App
    Properties:
      Name: NextJs Sample
      BasicAuthConfig:
        EnableBasicAuth: false
      BuildSpec: |
        version: "1.0"
        appRoot: app
        frontend:
          phases:
            preBuild:
              commands:
                - npm ci
            build:
              commands:
                - npm run build
          artifacts:
            baseDirectory: .next
            files:
              - "**/*"
          cache:
            paths:
              - node_modules/**/*
      CustomRules:
        - Source: /<*>
          Status: 404-200
          Target: "\t/index.html"
      EnableBranchAutoDeletion: true
      IAMServiceRole:
        Fn::GetAtt:
          - SampleRoleED81C780
          - Arn
      OauthToken: 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
      Repository: https://github.com/philschmid/nextjs-amplify-cdk-sample
    Metadata:
      aws:cdk:path: AmplifyHostingStack/Sample/Resource
  Samplemain4992BB11:
    Type: AWS::Amplify::Branch
    Properties:
      AppId:
        Fn::GetAtt:
          - Sample9DACD4DE
          - AppId
      BranchName: main
      EnableAutoBuild: true
      EnablePullRequestPreview: true
      Stage: PRODUCTION
    Metadata:
      aws:cdk:path: AmplifyHostingStack/Sample/main/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/z2NWw7CIBBF19J/mIpGv30soEldgBkpTWkpkAIaQ9i7pRK/bnLu3DN7ODKIrMK3o7ybqJJPiHePfCIrekSJM8TWKEFuvc6ZCM5Wyf4DcSUXa3NxXVDzISXSCmfCwrfrJngb/LYrNBFGUdkBYVedy8c6Z1GWMmbrX6lNJ2B09YudgB3W5eikpEvQXs4C2l9+AdNWapHHAAAA
    Metadata:
      aws:cdk:path: AmplifyHostingStack/CDKMetadata/Default
Outputs:
  appId:
    Value:
      Fn::GetAtt:
        - Sample9DACD4DE
        - AppId
  appDomain:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Fn::GetAtt:
              - Samplemain4992BB11
              - BranchName
          - "."
          - Fn::GetAtt:
              - Sample9DACD4DE
              - AppId
          - .amplifyapp.com
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

